BEGIN TRANSACTION;
CREATE TABLE `TRANSPORT` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL UNIQUE
);
CREATE TABLE `STOP` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`addressId`	INTEGER NOT NULL,
        FOREIGN KEY(addressId) REFERENCES ADDRESS(id)
);
CREATE TABLE `STOPLINE` (
	`stopId`	INTEGER NOT NULL,
	`lineId`	INTEGER NOT NULL,
        FOREIGN KEY(stopId) REFERENCES STOP(id),
        FOREIGN KEY(lineId) REFERENCES LINE(id),
        PRIMARY KEY(stopId, lineId)
    
);
CREATE TABLE "ROUTE_STEPS" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`route`	INTEGER NOT NULL,
	`origin`	INTEGER NOT NULL,
	`destiny`	INTEGER
);
CREATE TABLE `ROUTE_FATHER` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`title`	TEXT NOT NULL,
	`description`	TEXT,
	`hashTag`	TEXT NOT NULL,
	`timeStamp`	TEXT,
	`creator`	INTEGER NOT NULL,
        FOREIGN KEY(creator) REFERENCES RAFTER(id)
);
CREATE TABLE `RATE` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`creator`	TEXT NOT NULL,
	`routeId`	INTEGER NOT NULL,
	`comment`	TEXT,
        FOREIGN KEY(creator) REFERENCES RAFTER(id),
        FOREIGN KEY(routeId) REFERENCES ROUTE_FATHER(id)
        
);
CREATE TABLE "RAFTER" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`rafterName`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`email`	TEXT NOT NULL UNIQUE,
	`registerDate`	TEXT NOT NULL
);
CREATE TABLE `LINE` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT NOT NULL,
	`transportId`	INTEGER,
         FOREIGN KEY(transportId) REFERENCES TRANSPORT(id)
);
CREATE TABLE "ADDRESS" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`zipCode`	TEXT NOT NULL,
	`roadType`	TEXT NOT NULL,
	`roadName`	TEXT NOT NULL
);
CREATE UNIQUE INDEX `addres_unique` ON `ADDRESS` (`zipCode` ,`roadName` );
COMMIT;
